version: '3.9'

services:
  database:
    image: mysql:8.0 # Usa la versión que prefieras
    container_name: mysql_notificacion_bd
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root12345
      MYSQL_DATABASE: NotificacionBD
      MYSQL_USER: BDFinalNoti
      MYSQL_PASSWORD: final@12345
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
